/**
 * BillSnap - Email Module
 * Send invoices and reports via email
 */

const Email = {
    config: {
        method: 'mailto' // mailto, smtp, sendgrid
    },

    /**
     * Load email configuration
     */
    async loadConfig() {
        const method = await DB.getSetting('email_method');
        this.config.method = method || 'mailto';
    },

    /**
     * Send invoice via email
     */
    async sendInvoice(invoice, recipientEmail) {
        const isEs = i18n?.getLang() === 'es';
        
        switch (this.config.method) {
            case 'mailto':
                return this.sendViaMailto(invoice, recipientEmail);
            case 'smtp':
                return this.sendViaSMTP(invoice, recipientEmail);
            case 'sendgrid':
                return this.sendViaSendGrid(invoice, recipientEmail);
            default:
                return this.sendViaMailto(invoice, recipientEmail);
        }
    },

    /**
     * Send via mailto (opens email client)
     */
    sendViaMailto(invoice, recipientEmail) {
        const isEs = i18n?.getLang() === 'es';
        const subject = encodeURIComponent(
            `${isEs ? 'Factura' : 'Invoice'} ${invoice.invoiceNumber || ''} - ${invoice.issuer?.name || ''}`
        );
        const body = encodeURIComponent(
            `${isEs ? 'Adjunto factura' : 'Attached invoice'}:\n\n` +
            `${isEs ? 'Número' : 'Number'}: ${invoice.invoiceNumber || '-'}\n` +
            `${isEs ? 'Fecha' : 'Date'}: ${invoice.date || '-'}\n` +
            `${isEs ? 'Emisor' : 'Issuer'}: ${invoice.issuer?.name || '-'}\n` +
            `${isEs ? 'Total' : 'Total'}: ${Helpers.formatCurrency(invoice.total)}\n\n` +
            `${isEs ? 'Generado por BillSnap' : 'Generated by BillSnap'}`
        );

        const mailtoLink = `mailto:${recipientEmail || ''}?subject=${subject}&body=${body}`;
        window.open(mailtoLink);
        
        return { success: true, method: 'mailto' };
    },

    /**
     * Send via SMTP (requires backend)
     */
    async sendViaSMTP(invoice, recipientEmail) {
        // In production, this would call a backend API
        console.log('SMTP sending requires backend server');
        return { success: false, message: 'SMTP requires backend server' };
    },

    /**
     * Send via SendGrid
     */
    async sendViaSendGrid(invoice, recipientEmail) {
        const apiKey = await DB.getSetting('sendgrid_key');
        if (!apiKey) {
            throw new Error('SendGrid API key not configured');
        }

        // In production, this would call SendGrid API
        console.log('SendGrid integration coming soon');
        return { success: false, message: 'SendGrid integration coming soon' };
    },

    /**
     * Render email button for invoice
     */
    renderEmailButton(invoiceId, lang = 'es') {
        const isEs = lang === 'es';
        return `
            <button class="btn btn-secondary btn-sm" onclick="app.emailInvoice('${invoiceId}')" title="${isEs ? 'Enviar por email' : 'Send via email'}">
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                    <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path>
                    <polyline points="22,6 12,13 2,6"></polyline>
                </svg>
            </button>
        `;
    }
};

// Make globally available
window.Email = Email;
